// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proiectChioranAndrei.Data;

#nullable disable

namespace proiectChioranAndrei.Migrations
{
    [DbContext(typeof(proiectChioranAndreiContext))]
    [Migration("20240105212533_OraseSiObiective")]
    partial class OraseSiObiective
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proiectChioranAndrei.Models.ObiectivTuristic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Numar")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrasID")
                        .HasColumnType("int");

                    b.Property<string>("Strada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("OrasID");

                    b.ToTable("ObiectivTuristic");
                });

            modelBuilder.Entity("proiectChioranAndrei.Models.Oras", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeOras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Oras");
                });

            modelBuilder.Entity("proiectChioranAndrei.Models.ObiectivTuristic", b =>
                {
                    b.HasOne("proiectChioranAndrei.Models.Oras", "Oras")
                        .WithMany("ObiectivTuristics")
                        .HasForeignKey("OrasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oras");
                });

            modelBuilder.Entity("proiectChioranAndrei.Models.Oras", b =>
                {
                    b.Navigation("ObiectivTuristics");
                });
#pragma warning restore 612, 618
        }
    }
}
